server:
  port: 8100

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/payment?createDatabaseIfNotExist=true
    username: root
    password: senha432
  jackson:
    default-property-inclusion: non_null
